name: fitai
description: "FitAI - AI-powered fitness app"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons:
  dio:
  firebase_analytics:
  firebase_core:
  firebase_crashlytics:
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_dotenv:
  flutter_local_notifications:
  flutter_riverpod:
  freezed_annotation:
  geolocator:
  go_router:
  google_maps_flutter:
  health:
  # UI Components
  lucide_icons: ^0.257.0
  image_picker: ^1.0.7
  image: ^4.1.7
  cached_network_image: ^3.3.1
  share_plus: ^7.2.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.68.0
  intl:
  json_annotation:
  local_auth:
  lottie:
  material_symbols_icons:
  mobile_scanner:
  path_provider:
  purchases_flutter:
  retrofit:
  rive:
  shared_preferences:
  supabase_flutter:
  uuid:
  connectivity_plus: ^6.0.5
dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  retrofit_generator: ^10.0.2
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/lottie/
    - assets/rive/
    - assets/placeholder/
    - .env.dev
    - .env.stg
    - .env.prod
