// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:fitai/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbbA3G0nK53htsg_Hgiovd_hG1mdpkRhU',
    appId: '1:12246511496:web:ad16593905cd7bc3e4543d',
    messagingSenderId: '12246511496',
    projectId: 'fit-ai-8f6be',
    authDomain: 'fit-ai-8f6be.firebaseapp.com',
    storageBucket: 'fit-ai-8f6be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbA3G0nK53htsg_Hgiovd_hG1mdpkRhU',
    appId: '1:12246511496:android:910873b1906ae1ece4543d',
    messagingSenderId: '12246511496',
    projectId: 'fit-ai-8f6be',
    storageBucket: 'fit-ai-8f6be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4z7cLVMOSSQLNCRKQ-o5nfCoc4g8FqzQ',
    appId: '1:12246511496:ios:ad16593905cd7bc3e4543d',
    messagingSenderId: '12246511496',
    projectId: 'fit-ai-8f6be',
    storageBucket: 'fit-ai-8f6be.firebasestorage.app',
    iosBundleId: 'com.codenesthorizon.FitAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4z7cLVMOSSQLNCRKQ-o5nfCoc4g8FqzQ',
    appId: '1:12246511496:ios:ad16593905cd7bc3e4543d',
    messagingSenderId: '12246511496',
    projectId: 'fit-ai-8f6be',
    storageBucket: 'fit-ai-8f6be.firebasestorage.app',
    iosBundleId: 'com.codenesthorizon.FitAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbbA3G0nK53htsg_Hgiovd_hG1mdpkRhU',
    appId: '1:12246511496:web:ad16593905cd7bc3e4543d',
    messagingSenderId: '12246511496',
    projectId: 'fit-ai-8f6be',
    authDomain: 'fit-ai-8f6be.firebaseapp.com',
    storageBucket: 'fit-ai-8f6be.firebasestorage.app',
  );
}
